# Generated by Django 5.1.3 on 2024-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_comment_recipecomment_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
