# Generated by Django 5.1.3 on 2024-11-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingredients', '0003_alter_recipesingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredient',
            name='measurement',
            field=models.CharField(max_length=50),
        ),
    ]
