# Generated by Django 5.1.3 on 2024-12-09 10:59

import My_Recipes.recipe_ingredients.validators
import My_Recipes.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingredients', '0003_alter_recipesingredient_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredient',
            name='measurement',
            field=models.CharField(max_length=20, validators=[My_Recipes.validators.IsItAlpha('Measurement value should be only letters!')]),
        ),
        migrations.AlterField(
            model_name='recipesingredient',
            name='quantity',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(1), My_Recipes.recipe_ingredients.validators.is_it_digit]),
        ),
    ]
