# Generated by Django 5.1.3 on 2024-11-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingredients', '0004_alter_recipesingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredient',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
