# Generated by Django 5.1.3 on 2024-12-09 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingredients', '0007_alter_recipesingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredient',
            name='quantity',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
