# Generated by Django 5.1.3 on 2024-12-03 06:58

import My_Recipes.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2), My_Recipes.validators.IsItAlpha('First name should be only letters!')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2), My_Recipes.validators.IsItAlpha('Last name should be only letters!')]),
        ),
        migrations.AlterField(
            model_name='recipesuser',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='recipesuser',
            name='username',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3), My_Recipes.validators.IsItAlpha('Username should contain only letters!')]),
        ),
    ]
