# Generated by Django 5.1.3 on 2024-12-06 10:01

import My_Recipes.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='About me:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2), My_Recipes.accounts.validators.EmptySpacesOrAlphaValidator('First name should be only letters with no spaces!')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2), My_Recipes.accounts.validators.EmptySpacesOrAlphaValidator('Last name should be only letters with no spaces!')]),
        ),
        migrations.AlterField(
            model_name='recipesuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email is already taken!'}, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='recipesuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username is already taken!'}, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3), My_Recipes.accounts.validators.EmptySpacesOrAlphaValidator('Username should contain only letters with no spaces!')]),
        ),
    ]
