# Generated by Django 5.1.3 on 2024-11-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipes_created_by_recipe'),
        ('reviews', '0002_alter_recipereview_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
