# Generated by Django 5.1.3 on 2024-11-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
