# Generated by Django 5.1.3 on 2024-12-06 10:01

import My_Recipes.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_cook_time_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), My_Recipes.validators.IsItAlpha('Title should be only letters!')]),
        ),
    ]
