# Generated by Django 5.1.3 on 2024-11-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='approved',
        ),
    ]
