# Generated by Django 5.1.3 on 2024-12-11 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_description_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(help_text='Cooking time in minutes...', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(help_text='Preparation time in minutes...', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(6)]),
        ),
    ]
