# Generated by Django 5.1.3 on 2024-12-11 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_cook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(help_text='Cooking time in minutes...', validators=[django.core.validators.MinValueValidator(1, message='Cooking time must be at least 1 minute.'), django.core.validators.MaxValueValidator(999999, message='Maximum 6 digits allowed for cooking time.')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(help_text='Preparation time in minutes...', validators=[django.core.validators.MinValueValidator(1, message='Preparation time must be at least 1 minute.'), django.core.validators.MaxValueValidator(999999, message='Maximum 6 digits allowed for preparation time.')]),
        ),
    ]
