# Generated by Django 5.1.3 on 2024-11-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='created_by',
        ),
    ]
