# Generated by Django 5.1.3 on 2024-12-03 06:58

import My_Recipes.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), My_Recipes.validators.IsItAlpha('Ingredient name should be only letters!')]),
        ),
    ]
