# Generated by Django 5.1.3 on 2024-12-03 06:58

import My_Recipes.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5), My_Recipes.validators.IsItAlpha('Category should be only letters!')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5), My_Recipes.validators.IsItAlpha('Title should be only letters!')]),
        ),
    ]
