# Generated by Django 5.1.3 on 2024-11-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
